package com.office.mall.entiy;

public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.first_letter
     *
     * @mbg.generated
     */
    private String firstLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.id
     *
     * @return the value of pms_brand.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.id
     *
     * @param id the value for pms_brand.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.name
     *
     * @return the value of pms_brand.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.name
     *
     * @param name the value for pms_brand.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.first_letter
     *
     * @return the value of pms_brand.first_letter
     *
     * @mbg.generated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.first_letter
     *
     * @param firstLetter the value for pms_brand.first_letter
     *
     * @mbg.generated
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.logo
     *
     * @return the value of pms_brand.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.logo
     *
     * @param logo the value for pms_brand.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}