package com.office.mall.entiy;

import java.math.BigDecimal;

public class Order extends OrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_amount
     *
     * @mbg.generated
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.discount_amount
     *
     * @mbg.generated
     */
    private BigDecimal discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_type
     *
     * @mbg.generated
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_company
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_sn
     *
     * @mbg.generated
     */
    private String deliverySn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.confirm_status
     *
     * @mbg.generated
     */
    private Integer confirmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.payment_time
     *
     * @mbg.generated
     */
    private Long paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_time
     *
     * @mbg.generated
     */
    private Long deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receive_time
     *
     * @mbg.generated
     */
    private Long receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.create_time
     *
     * @return the value of oms_order.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.create_time
     *
     * @param createTime the value for oms_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.total_amount
     *
     * @return the value of oms_order.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.total_amount
     *
     * @param totalAmount the value for oms_order.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_amount
     *
     * @return the value of oms_order.pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_amount
     *
     * @param payAmount the value for oms_order.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.discount_amount
     *
     * @return the value of oms_order.discount_amount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.discount_amount
     *
     * @param discountAmount the value for oms_order.discount_amount
     *
     * @mbg.generated
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_type
     *
     * @return the value of oms_order.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_type
     *
     * @param payType the value for oms_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.status
     *
     * @return the value of oms_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.status
     *
     * @param status the value for oms_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_company
     *
     * @return the value of oms_order.delivery_company
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_company
     *
     * @param deliveryCompany the value for oms_order.delivery_company
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_sn
     *
     * @return the value of oms_order.delivery_sn
     *
     * @mbg.generated
     */
    public String getDeliverySn() {
        return deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_sn
     *
     * @param deliverySn the value for oms_order.delivery_sn
     *
     * @mbg.generated
     */
    public void setDeliverySn(String deliverySn) {
        this.deliverySn = deliverySn == null ? null : deliverySn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.confirm_status
     *
     * @return the value of oms_order.confirm_status
     *
     * @mbg.generated
     */
    public Integer getConfirmStatus() {
        return confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.confirm_status
     *
     * @param confirmStatus the value for oms_order.confirm_status
     *
     * @mbg.generated
     */
    public void setConfirmStatus(Integer confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.payment_time
     *
     * @return the value of oms_order.payment_time
     *
     * @mbg.generated
     */
    public Long getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.payment_time
     *
     * @param paymentTime the value for oms_order.payment_time
     *
     * @mbg.generated
     */
    public void setPaymentTime(Long paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_time
     *
     * @return the value of oms_order.delivery_time
     *
     * @mbg.generated
     */
    public Long getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_time
     *
     * @param deliveryTime the value for oms_order.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(Long deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receive_time
     *
     * @return the value of oms_order.receive_time
     *
     * @mbg.generated
     */
    public Long getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receive_time
     *
     * @param receiveTime the value for oms_order.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Long receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.modify_time
     *
     * @return the value of oms_order.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.modify_time
     *
     * @param modifyTime the value for oms_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}