package com.office.mall.entiy;

public class ProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_category_id
     *
     * @mbg.generated
     */
    private Integer productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_specifications_id
     *
     * @mbg.generated
     */
    private Integer productSpecificationsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.id
     *
     * @return the value of pms_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.id
     *
     * @param id the value for pms_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.shop_id
     *
     * @return the value of pms_product.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.shop_id
     *
     * @param shopId the value for pms_product.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.brand_id
     *
     * @return the value of pms_product.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.brand_id
     *
     * @param brandId the value for pms_product.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.product_category_id
     *
     * @return the value of pms_product.product_category_id
     *
     * @mbg.generated
     */
    public Integer getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.product_category_id
     *
     * @param productCategoryId the value for pms_product.product_category_id
     *
     * @mbg.generated
     */
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product.product_specifications_id
     *
     * @return the value of pms_product.product_specifications_id
     *
     * @mbg.generated
     */
    public Integer getProductSpecificationsId() {
        return productSpecificationsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product.product_specifications_id
     *
     * @param productSpecificationsId the value for pms_product.product_specifications_id
     *
     * @mbg.generated
     */
    public void setProductSpecificationsId(Integer productSpecificationsId) {
        this.productSpecificationsId = productSpecificationsId;
    }
}