package com.office.mall.dao;

import com.office.mall.entiy.Cart;
import com.office.mall.request.CartRequest;

import java.util.List;

public interface CartMapper {
    List<Cart> queryList();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_cart
     *
     * @mbg.generated
     */
    int insert(CartRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_cart
     *
     * @mbg.generated
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);
}