package com.office.mall.dao;

import com.office.mall.entiy.Category;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category
     *
     * @mbg.generated
     */
    int insert(Category record);

    List<Category> queryList(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_category
     *
     * @mbg.generated
     */
    int insertSelective(Category record);
}