package com.office.mall.dao;

import com.office.mall.entiy.Specifications;

public interface SpecificationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_specifications
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_specifications
     *
     * @mbg.generated
     */
    int insert(Specifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_specifications
     *
     * @mbg.generated
     */
    int insertSelective(Specifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_specifications
     *
     * @mbg.generated
     */
    Specifications selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_specifications
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Specifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_specifications
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Specifications record);
}