package com.office.mall.request;

public class SpecRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_specifications.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_specifications.spec_name
     *
     * @mbg.generated
     */
    private String specName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_specifications.id
     *
     * @return the value of pms_product_specifications.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_specifications.id
     *
     * @param id the value for pms_product_specifications.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_specifications.spec_name
     *
     * @return the value of pms_product_specifications.spec_name
     *
     * @mbg.generated
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_specifications.spec_name
     *
     * @param specName the value for pms_product_specifications.spec_name
     *
     * @mbg.generated
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }
}
